/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 18
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_colon = 1,
  anon_sym_AT = 2,
  sym_name = 3,
  sym_arg = 4,
  sym__newline = 5,
  sym_indent = 6,
  sym_dedent = 7,
  sym_text = 8,
  sym_source_file = 9,
  sym_heading_block = 10,
  sym_heading_line = 11,
  sym_task_block = 12,
  sym_task_line = 13,
  sym_tag_only_line = 14,
  sym_tag = 15,
  aux_sym_source_file_repeat1 = 16,
  aux_sym_heading_line_repeat1 = 17,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_colon] = "colon",
  [anon_sym_AT] = "@",
  [sym_name] = "name",
  [sym_arg] = "arg",
  [sym__newline] = "_newline",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_heading_block] = "heading_block",
  [sym_heading_line] = "heading_line",
  [sym_task_block] = "task_block",
  [sym_task_line] = "task_line",
  [sym_tag_only_line] = "tag_only_line",
  [sym_tag] = "tag",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_heading_line_repeat1] = "heading_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_colon] = sym_colon,
  [anon_sym_AT] = anon_sym_AT,
  [sym_name] = sym_name,
  [sym_arg] = sym_arg,
  [sym__newline] = sym__newline,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_heading_block] = sym_heading_block,
  [sym_heading_line] = sym_heading_line,
  [sym_task_block] = sym_task_block,
  [sym_task_line] = sym_task_line,
  [sym_tag_only_line] = sym_tag_only_line,
  [sym_tag] = sym_tag,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_heading_line_repeat1] = aux_sym_heading_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_block] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_line] = {
    .visible = true,
    .named = true,
  },
  [sym_task_block] = {
    .visible = true,
    .named = true,
  },
  [sym_task_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_only_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_name = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_name] = "name",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_text, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_arg, 2},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 8,
  [9] = 3,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 12,
  [18] = 18,
  [19] = 14,
  [20] = 16,
  [21] = 21,
  [22] = 22,
  [23] = 15,
  [24] = 22,
  [25] = 18,
  [26] = 21,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 31,
  [33] = 30,
  [34] = 28,
  [35] = 27,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 38,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '(') ADVANCE(1);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '@') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_colon);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_arg);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 5},
  [11] = {.lex_state = 0, .external_lex_state = 5},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 0, .external_lex_state = 6},
  [15] = {.lex_state = 0, .external_lex_state = 6},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 0, .external_lex_state = 5},
  [18] = {.lex_state = 0, .external_lex_state = 6},
  [19] = {.lex_state = 0, .external_lex_state = 7},
  [20] = {.lex_state = 0, .external_lex_state = 5},
  [21] = {.lex_state = 0, .external_lex_state = 5},
  [22] = {.lex_state = 0, .external_lex_state = 5},
  [23] = {.lex_state = 0, .external_lex_state = 7},
  [24] = {.lex_state = 0, .external_lex_state = 5},
  [25] = {.lex_state = 0, .external_lex_state = 7},
  [26] = {.lex_state = 0, .external_lex_state = 5},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 3},
  [29] = {.lex_state = 0, .external_lex_state = 5},
  [30] = {.lex_state = 0, .external_lex_state = 3},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 0, .external_lex_state = 4},
  [34] = {.lex_state = 0, .external_lex_state = 4},
  [35] = {.lex_state = 0, .external_lex_state = 4},
  [36] = {.lex_state = 0, .external_lex_state = 5},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 0, .external_lex_state = 8},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0, .external_lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_arg] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(39),
    [sym_heading_block] = STATE(4),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(4),
    [sym_tag_only_line] = STATE(4),
    [sym_tag] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_heading_line_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_AT] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [sym_text] = ACTIONS(9),
  },
  [STATE(2)] = {
    [sym_heading_block] = STATE(5),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(5),
    [sym_tag_only_line] = STATE(5),
    [sym_tag] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(5),
    [aux_sym_heading_line_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(5),
    [sym_text] = ACTIONS(9),
  },
  [STATE(3)] = {
    [sym_heading_block] = STATE(8),
    [sym_heading_line] = STATE(19),
    [sym_task_block] = STATE(38),
    [sym_task_line] = STATE(8),
    [sym_tag_only_line] = STATE(8),
    [sym_tag] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_heading_line_repeat1] = STATE(12),
    [anon_sym_AT] = ACTIONS(5),
    [sym_text] = ACTIONS(13),
  },
  [STATE(4)] = {
    [sym_heading_block] = STATE(6),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(6),
    [sym_tag_only_line] = STATE(6),
    [sym_tag] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_line_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(5),
    [sym_text] = ACTIONS(9),
  },
  [STATE(5)] = {
    [sym_heading_block] = STATE(6),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(6),
    [sym_tag_only_line] = STATE(6),
    [sym_tag] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_line_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(15),
    [anon_sym_AT] = ACTIONS(5),
    [sym_text] = ACTIONS(9),
  },
  [STATE(6)] = {
    [sym_heading_block] = STATE(6),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(6),
    [sym_tag_only_line] = STATE(6),
    [sym_tag] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_line_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(19),
    [sym_text] = ACTIONS(22),
  },
  [STATE(7)] = {
    [sym_heading_block] = STATE(7),
    [sym_heading_line] = STATE(19),
    [sym_task_line] = STATE(7),
    [sym_tag_only_line] = STATE(7),
    [sym_tag] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_heading_line_repeat1] = STATE(12),
    [anon_sym_AT] = ACTIONS(19),
    [sym_dedent] = ACTIONS(17),
    [sym_text] = ACTIONS(25),
  },
  [STATE(8)] = {
    [sym_heading_block] = STATE(7),
    [sym_heading_line] = STATE(19),
    [sym_task_line] = STATE(7),
    [sym_tag_only_line] = STATE(7),
    [sym_tag] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_heading_line_repeat1] = STATE(12),
    [anon_sym_AT] = ACTIONS(5),
    [sym_dedent] = ACTIONS(28),
    [sym_text] = ACTIONS(13),
  },
  [STATE(9)] = {
    [sym_heading_block] = STATE(8),
    [sym_heading_line] = STATE(19),
    [sym_task_block] = STATE(40),
    [sym_task_line] = STATE(8),
    [sym_tag_only_line] = STATE(8),
    [sym_tag] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_heading_line_repeat1] = STATE(12),
    [anon_sym_AT] = ACTIONS(5),
    [sym_text] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(30), 1,
      sym_colon,
    ACTIONS(32), 1,
      sym__newline,
    STATE(26), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [14] = 4,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(34), 1,
      sym_colon,
    ACTIONS(36), 1,
      sym__newline,
    STATE(21), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [28] = 3,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(38), 1,
      sym__newline,
    STATE(13), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [39] = 3,
    ACTIONS(40), 1,
      anon_sym_AT,
    ACTIONS(43), 1,
      sym__newline,
    STATE(13), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [50] = 2,
    ACTIONS(47), 1,
      sym_indent,
    ACTIONS(45), 3,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_AT,
  [59] = 1,
    ACTIONS(49), 4,
      sym_indent,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_AT,
  [66] = 3,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(51), 1,
      sym__newline,
    STATE(13), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [77] = 3,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(53), 1,
      sym__newline,
    STATE(13), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [88] = 1,
    ACTIONS(55), 4,
      sym_indent,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_AT,
  [95] = 2,
    ACTIONS(57), 1,
      sym_indent,
    ACTIONS(45), 3,
      sym_dedent,
      sym_text,
      anon_sym_AT,
  [104] = 3,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(59), 1,
      sym__newline,
    STATE(13), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [115] = 3,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(61), 1,
      sym__newline,
    STATE(13), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [126] = 3,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(63), 1,
      sym__newline,
    STATE(20), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [137] = 1,
    ACTIONS(49), 4,
      sym_indent,
      sym_dedent,
      sym_text,
      anon_sym_AT,
  [144] = 3,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(65), 1,
      sym__newline,
    STATE(16), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [155] = 1,
    ACTIONS(55), 4,
      sym_indent,
      sym_dedent,
      sym_text,
      anon_sym_AT,
  [162] = 3,
    ACTIONS(5), 1,
      anon_sym_AT,
    ACTIONS(67), 1,
      sym__newline,
    STATE(13), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [173] = 1,
    ACTIONS(69), 3,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_AT,
  [179] = 1,
    ACTIONS(71), 3,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_AT,
  [185] = 2,
    ACTIONS(75), 1,
      sym_arg,
    ACTIONS(73), 2,
      sym__newline,
      anon_sym_AT,
  [193] = 1,
    ACTIONS(77), 3,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_AT,
  [199] = 1,
    ACTIONS(79), 3,
      sym_dedent,
      sym_text,
      anon_sym_AT,
  [205] = 1,
    ACTIONS(79), 3,
      sym_text,
      ts_builtin_sym_end,
      anon_sym_AT,
  [211] = 1,
    ACTIONS(77), 3,
      sym_dedent,
      sym_text,
      anon_sym_AT,
  [217] = 1,
    ACTIONS(71), 3,
      sym_dedent,
      sym_text,
      anon_sym_AT,
  [223] = 1,
    ACTIONS(69), 3,
      sym_dedent,
      sym_text,
      anon_sym_AT,
  [229] = 1,
    ACTIONS(81), 2,
      sym__newline,
      anon_sym_AT,
  [234] = 1,
    ACTIONS(83), 1,
      sym_name,
  [238] = 1,
    ACTIONS(85), 1,
      sym_dedent,
  [242] = 1,
    ACTIONS(87), 1,
      ts_builtin_sym_end,
  [246] = 1,
    ACTIONS(89), 1,
      sym_dedent,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 14,
  [SMALL_STATE(12)] = 28,
  [SMALL_STATE(13)] = 39,
  [SMALL_STATE(14)] = 50,
  [SMALL_STATE(15)] = 59,
  [SMALL_STATE(16)] = 66,
  [SMALL_STATE(17)] = 77,
  [SMALL_STATE(18)] = 88,
  [SMALL_STATE(19)] = 95,
  [SMALL_STATE(20)] = 104,
  [SMALL_STATE(21)] = 115,
  [SMALL_STATE(22)] = 126,
  [SMALL_STATE(23)] = 137,
  [SMALL_STATE(24)] = 144,
  [SMALL_STATE(25)] = 155,
  [SMALL_STATE(26)] = 162,
  [SMALL_STATE(27)] = 173,
  [SMALL_STATE(28)] = 179,
  [SMALL_STATE(29)] = 185,
  [SMALL_STATE(30)] = 193,
  [SMALL_STATE(31)] = 199,
  [SMALL_STATE(32)] = 205,
  [SMALL_STATE(33)] = 211,
  [SMALL_STATE(34)] = 217,
  [SMALL_STATE(35)] = 223,
  [SMALL_STATE(36)] = 229,
  [SMALL_STATE(37)] = 234,
  [SMALL_STATE(38)] = 238,
  [SMALL_STATE(39)] = 242,
  [SMALL_STATE(40)] = 246,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [19] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [28] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_block, 1, 0, 0),
  [30] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_block, 1, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 3, 0, 1),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 4, 0, 1),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [61] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [63] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_line, 3, 0, 1),
  [71] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_only_line, 2, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 2),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_block, 4, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_line, 2, 0, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 3),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [87] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token_indent = 1,
  ts_external_token_dedent = 2,
  ts_external_token_text = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
  },
  [6] = {
    [ts_external_token_indent] = true,
    [ts_external_token_text] = true,
  },
  [7] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [8] = {
    [ts_external_token_dedent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_todo_external_scanner_create(void);
void tree_sitter_todo_external_scanner_destroy(void *);
bool tree_sitter_todo_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_todo_external_scanner_serialize(void *, char *);
void tree_sitter_todo_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_todo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_todo_external_scanner_create,
      tree_sitter_todo_external_scanner_destroy,
      tree_sitter_todo_external_scanner_scan,
      tree_sitter_todo_external_scanner_serialize,
      tree_sitter_todo_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "todo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
