/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 49
#define LARGE_STATE_COUNT 10
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_colon = 1,
  anon_sym_AT = 2,
  sym_name = 3,
  sym_arg = 4,
  sym__newline = 5,
  sym_indent = 6,
  sym_dedent = 7,
  sym_text = 8,
  sym_source_file = 9,
  sym_heading_block = 10,
  sym_heading_line = 11,
  sym_task_block = 12,
  sym_task_line = 13,
  sym_tag = 14,
  aux_sym_source_file_repeat1 = 15,
  aux_sym_heading_line_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_colon] = "colon",
  [anon_sym_AT] = "@",
  [sym_name] = "name",
  [sym_arg] = "arg",
  [sym__newline] = "_newline",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_heading_block] = "heading_block",
  [sym_heading_line] = "heading_line",
  [sym_task_block] = "task_block",
  [sym_task_line] = "task_line",
  [sym_tag] = "tag",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_heading_line_repeat1] = "heading_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_colon] = sym_colon,
  [anon_sym_AT] = anon_sym_AT,
  [sym_name] = sym_name,
  [sym_arg] = sym_arg,
  [sym__newline] = sym__newline,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_heading_block] = sym_heading_block,
  [sym_heading_line] = sym_heading_line,
  [sym_task_block] = sym_task_block,
  [sym_task_line] = sym_task_line,
  [sym_tag] = sym_tag,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_heading_line_repeat1] = aux_sym_heading_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_block] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_line] = {
    .visible = true,
    .named = true,
  },
  [sym_task_block] = {
    .visible = true,
    .named = true,
  },
  [sym_task_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_name = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_name] = "name",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_text, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_arg, 2},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 5,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 11,
  [16] = 16,
  [17] = 14,
  [18] = 12,
  [19] = 13,
  [20] = 10,
  [21] = 16,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 22,
  [27] = 27,
  [28] = 25,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 27,
  [35] = 31,
  [36] = 36,
  [37] = 29,
  [38] = 23,
  [39] = 32,
  [40] = 24,
  [41] = 33,
  [42] = 36,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 46,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '(') ADVANCE(1);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '@') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(7);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(') ADVANCE(6);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_colon);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(') ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_arg);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 5},
  [11] = {.lex_state = 0, .external_lex_state = 6},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 0, .external_lex_state = 5},
  [15] = {.lex_state = 0, .external_lex_state = 6},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 0, .external_lex_state = 7},
  [18] = {.lex_state = 0, .external_lex_state = 7},
  [19] = {.lex_state = 0, .external_lex_state = 7},
  [20] = {.lex_state = 0, .external_lex_state = 7},
  [21] = {.lex_state = 0, .external_lex_state = 7},
  [22] = {.lex_state = 0, .external_lex_state = 4},
  [23] = {.lex_state = 0, .external_lex_state = 6},
  [24] = {.lex_state = 0, .external_lex_state = 6},
  [25] = {.lex_state = 0, .external_lex_state = 3},
  [26] = {.lex_state = 0, .external_lex_state = 3},
  [27] = {.lex_state = 0, .external_lex_state = 4},
  [28] = {.lex_state = 0, .external_lex_state = 4},
  [29] = {.lex_state = 0, .external_lex_state = 6},
  [30] = {.lex_state = 0, .external_lex_state = 6},
  [31] = {.lex_state = 0, .external_lex_state = 4},
  [32] = {.lex_state = 0, .external_lex_state = 6},
  [33] = {.lex_state = 0, .external_lex_state = 6},
  [34] = {.lex_state = 0, .external_lex_state = 3},
  [35] = {.lex_state = 0, .external_lex_state = 3},
  [36] = {.lex_state = 0, .external_lex_state = 6},
  [37] = {.lex_state = 0, .external_lex_state = 6},
  [38] = {.lex_state = 0, .external_lex_state = 6},
  [39] = {.lex_state = 0, .external_lex_state = 6},
  [40] = {.lex_state = 0, .external_lex_state = 6},
  [41] = {.lex_state = 0, .external_lex_state = 6},
  [42] = {.lex_state = 0, .external_lex_state = 6},
  [43] = {.lex_state = 0, .external_lex_state = 6},
  [44] = {.lex_state = 0, .external_lex_state = 6},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0, .external_lex_state = 8},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 0, .external_lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_arg] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(45),
    [sym_heading_block] = STATE(2),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(2),
    [sym_tag] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_heading_line_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_colon] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [sym__newline] = ACTIONS(9),
    [sym_text] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_heading_block] = STATE(6),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(6),
    [sym_tag] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_line_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_colon] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [sym_text] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_heading_block] = STATE(6),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(6),
    [sym_tag] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_line_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_colon] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [sym_text] = ACTIONS(11),
  },
  [STATE(4)] = {
    [sym_heading_block] = STATE(3),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(3),
    [sym_tag] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_heading_line_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_colon] = ACTIONS(5),
    [anon_sym_AT] = ACTIONS(7),
    [sym_text] = ACTIONS(11),
  },
  [STATE(5)] = {
    [sym_heading_block] = STATE(7),
    [sym_heading_line] = STATE(17),
    [sym_task_block] = STATE(46),
    [sym_task_line] = STATE(7),
    [sym_tag] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_heading_line_repeat1] = STATE(37),
    [sym_colon] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(7),
    [sym_text] = ACTIONS(19),
  },
  [STATE(6)] = {
    [sym_heading_block] = STATE(6),
    [sym_heading_line] = STATE(14),
    [sym_task_line] = STATE(6),
    [sym_tag] = STATE(29),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_heading_line_repeat1] = STATE(29),
    [ts_builtin_sym_end] = ACTIONS(21),
    [sym_colon] = ACTIONS(23),
    [anon_sym_AT] = ACTIONS(26),
    [sym_text] = ACTIONS(29),
  },
  [STATE(7)] = {
    [sym_heading_block] = STATE(8),
    [sym_heading_line] = STATE(17),
    [sym_task_line] = STATE(8),
    [sym_tag] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_heading_line_repeat1] = STATE(37),
    [sym_colon] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(7),
    [sym_dedent] = ACTIONS(32),
    [sym_text] = ACTIONS(19),
  },
  [STATE(8)] = {
    [sym_heading_block] = STATE(8),
    [sym_heading_line] = STATE(17),
    [sym_task_line] = STATE(8),
    [sym_tag] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_heading_line_repeat1] = STATE(37),
    [sym_colon] = ACTIONS(34),
    [anon_sym_AT] = ACTIONS(26),
    [sym_dedent] = ACTIONS(21),
    [sym_text] = ACTIONS(37),
  },
  [STATE(9)] = {
    [sym_heading_block] = STATE(7),
    [sym_heading_line] = STATE(17),
    [sym_task_block] = STATE(48),
    [sym_task_line] = STATE(7),
    [sym_tag] = STATE(37),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_heading_line_repeat1] = STATE(37),
    [sym_colon] = ACTIONS(17),
    [anon_sym_AT] = ACTIONS(7),
    [sym_text] = ACTIONS(19),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 1,
    ACTIONS(40), 5,
      sym_indent,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [8] = 4,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(42), 1,
      sym_colon,
    ACTIONS(44), 1,
      sym__newline,
    STATE(39), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [22] = 1,
    ACTIONS(46), 5,
      sym_indent,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [30] = 1,
    ACTIONS(48), 5,
      sym_indent,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [38] = 2,
    ACTIONS(52), 1,
      sym_indent,
    ACTIONS(50), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [48] = 4,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(54), 1,
      sym_colon,
    ACTIONS(56), 1,
      sym__newline,
    STATE(32), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [62] = 1,
    ACTIONS(58), 5,
      sym_indent,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [70] = 2,
    ACTIONS(60), 1,
      sym_indent,
    ACTIONS(50), 4,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [80] = 1,
    ACTIONS(46), 5,
      sym_indent,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [88] = 1,
    ACTIONS(48), 5,
      sym_indent,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [96] = 1,
    ACTIONS(40), 5,
      sym_indent,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [104] = 1,
    ACTIONS(58), 5,
      sym_indent,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [112] = 1,
    ACTIONS(62), 4,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [119] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(64), 1,
      sym__newline,
    STATE(33), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [130] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(66), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [141] = 1,
    ACTIONS(68), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [148] = 1,
    ACTIONS(62), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [155] = 1,
    ACTIONS(70), 4,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [162] = 1,
    ACTIONS(68), 4,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [169] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(72), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [180] = 3,
    ACTIONS(74), 1,
      anon_sym_AT,
    ACTIONS(77), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [191] = 1,
    ACTIONS(79), 4,
      sym_dedent,
      sym_text,
      sym_colon,
      anon_sym_AT,
  [198] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(81), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [209] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(83), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [220] = 1,
    ACTIONS(70), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [227] = 1,
    ACTIONS(79), 4,
      sym_text,
      ts_builtin_sym_end,
      sym_colon,
      anon_sym_AT,
  [234] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(85), 1,
      sym__newline,
    STATE(40), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [245] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(87), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [256] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(89), 1,
      sym__newline,
    STATE(41), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [267] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(91), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [278] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(93), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [289] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(95), 1,
      sym__newline,
    STATE(30), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [300] = 3,
    ACTIONS(7), 1,
      anon_sym_AT,
    ACTIONS(97), 1,
      sym__newline,
    STATE(24), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [311] = 2,
    ACTIONS(101), 1,
      sym_arg,
    ACTIONS(99), 2,
      sym__newline,
      anon_sym_AT,
  [319] = 1,
    ACTIONS(103), 2,
      sym__newline,
      anon_sym_AT,
  [324] = 1,
    ACTIONS(105), 1,
      ts_builtin_sym_end,
  [328] = 1,
    ACTIONS(107), 1,
      sym_dedent,
  [332] = 1,
    ACTIONS(109), 1,
      sym_name,
  [336] = 1,
    ACTIONS(111), 1,
      sym_dedent,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(10)] = 0,
  [SMALL_STATE(11)] = 8,
  [SMALL_STATE(12)] = 22,
  [SMALL_STATE(13)] = 30,
  [SMALL_STATE(14)] = 38,
  [SMALL_STATE(15)] = 48,
  [SMALL_STATE(16)] = 62,
  [SMALL_STATE(17)] = 70,
  [SMALL_STATE(18)] = 80,
  [SMALL_STATE(19)] = 88,
  [SMALL_STATE(20)] = 96,
  [SMALL_STATE(21)] = 104,
  [SMALL_STATE(22)] = 112,
  [SMALL_STATE(23)] = 119,
  [SMALL_STATE(24)] = 130,
  [SMALL_STATE(25)] = 141,
  [SMALL_STATE(26)] = 148,
  [SMALL_STATE(27)] = 155,
  [SMALL_STATE(28)] = 162,
  [SMALL_STATE(29)] = 169,
  [SMALL_STATE(30)] = 180,
  [SMALL_STATE(31)] = 191,
  [SMALL_STATE(32)] = 198,
  [SMALL_STATE(33)] = 209,
  [SMALL_STATE(34)] = 220,
  [SMALL_STATE(35)] = 227,
  [SMALL_STATE(36)] = 234,
  [SMALL_STATE(37)] = 245,
  [SMALL_STATE(38)] = 256,
  [SMALL_STATE(39)] = 267,
  [SMALL_STATE(40)] = 278,
  [SMALL_STATE(41)] = 289,
  [SMALL_STATE(42)] = 300,
  [SMALL_STATE(43)] = 311,
  [SMALL_STATE(44)] = 319,
  [SMALL_STATE(45)] = 324,
  [SMALL_STATE(46)] = 328,
  [SMALL_STATE(47)] = 332,
  [SMALL_STATE(48)] = 336,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [21] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [26] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [29] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [32] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_block, 1, 0, 0),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [40] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 3, 0, 0),
  [42] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [46] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 2, 0, 0),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 3, 0, 1),
  [50] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_block, 1, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 4, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_block, 4, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_line, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_line, 2, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0), SHIFT_REPEAT(47),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_line, 3, 0, 1),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [91] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 2),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [103] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 3),
  [105] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token_indent = 1,
  ts_external_token_dedent = 2,
  ts_external_token_text = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [5] = {
    [ts_external_token_indent] = true,
    [ts_external_token_text] = true,
  },
  [6] = {
    [ts_external_token__newline] = true,
  },
  [7] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [8] = {
    [ts_external_token_dedent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_todo_external_scanner_create(void);
void tree_sitter_todo_external_scanner_destroy(void *);
bool tree_sitter_todo_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_todo_external_scanner_serialize(void *, char *);
void tree_sitter_todo_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_todo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_todo_external_scanner_create,
      tree_sitter_todo_external_scanner_destroy,
      tree_sitter_todo_external_scanner_scan,
      tree_sitter_todo_external_scanner_serialize,
      tree_sitter_todo_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "todo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
