/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 37
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 17
#define ALIAS_COUNT 0
#define TOKEN_COUNT 9
#define EXTERNAL_TOKEN_COUNT 4
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_colon = 1,
  anon_sym_AT = 2,
  sym_name = 3,
  sym_arg = 4,
  sym__newline = 5,
  sym_indent = 6,
  sym_dedent = 7,
  sym_text = 8,
  sym_source_file = 9,
  sym_heading_block = 10,
  sym_heading_line = 11,
  sym_task_block = 12,
  sym_task_line = 13,
  sym_tag = 14,
  aux_sym_source_file_repeat1 = 15,
  aux_sym_heading_line_repeat1 = 16,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_colon] = "colon",
  [anon_sym_AT] = "@",
  [sym_name] = "name",
  [sym_arg] = "arg",
  [sym__newline] = "_newline",
  [sym_indent] = "indent",
  [sym_dedent] = "dedent",
  [sym_text] = "text",
  [sym_source_file] = "source_file",
  [sym_heading_block] = "heading_block",
  [sym_heading_line] = "heading_line",
  [sym_task_block] = "task_block",
  [sym_task_line] = "task_line",
  [sym_tag] = "tag",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_heading_line_repeat1] = "heading_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_colon] = sym_colon,
  [anon_sym_AT] = anon_sym_AT,
  [sym_name] = sym_name,
  [sym_arg] = sym_arg,
  [sym__newline] = sym__newline,
  [sym_indent] = sym_indent,
  [sym_dedent] = sym_dedent,
  [sym_text] = sym_text,
  [sym_source_file] = sym_source_file,
  [sym_heading_block] = sym_heading_block,
  [sym_heading_line] = sym_heading_line,
  [sym_task_block] = sym_task_block,
  [sym_task_line] = sym_task_line,
  [sym_tag] = sym_tag,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_heading_line_repeat1] = aux_sym_heading_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_colon] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [sym_name] = {
    .visible = true,
    .named = true,
  },
  [sym_arg] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_dedent] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_block] = {
    .visible = true,
    .named = true,
  },
  [sym_heading_line] = {
    .visible = true,
    .named = true,
  },
  [sym_task_block] = {
    .visible = true,
    .named = true,
  },
  [sym_task_line] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_heading_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_arg = 1,
  field_name = 2,
  field_text = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_arg] = "arg",
  [field_name] = "name",
  [field_text] = "text",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_text, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_arg, 2},
    {field_name, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 5,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 12,
  [17] = 13,
  [18] = 14,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 21,
  [23] = 23,
  [24] = 20,
  [25] = 23,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 27,
  [31] = 28,
  [32] = 26,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 35,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(3);
      if (lookahead == '(') ADVANCE(1);
      if (lookahead == ':') ADVANCE(4);
      if (lookahead == '@') ADVANCE(5);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == ')') ADVANCE(7);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '(' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 3:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 4:
      ACCEPT_TOKEN(sym_colon);
      END_STATE();
    case 5:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(sym_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '(' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym_arg);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 3},
  [3] = {.lex_state = 0, .external_lex_state = 3},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 3},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 4},
  [9] = {.lex_state = 0, .external_lex_state = 3},
  [10] = {.lex_state = 0, .external_lex_state = 5},
  [11] = {.lex_state = 0, .external_lex_state = 5},
  [12] = {.lex_state = 0, .external_lex_state = 5},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 0, .external_lex_state = 5},
  [15] = {.lex_state = 0, .external_lex_state = 5},
  [16] = {.lex_state = 0, .external_lex_state = 5},
  [17] = {.lex_state = 0, .external_lex_state = 5},
  [18] = {.lex_state = 0, .external_lex_state = 5},
  [19] = {.lex_state = 0, .external_lex_state = 5},
  [20] = {.lex_state = 0, .external_lex_state = 6},
  [21] = {.lex_state = 0, .external_lex_state = 6},
  [22] = {.lex_state = 0, .external_lex_state = 7},
  [23] = {.lex_state = 0, .external_lex_state = 7},
  [24] = {.lex_state = 0, .external_lex_state = 7},
  [25] = {.lex_state = 0, .external_lex_state = 6},
  [26] = {.lex_state = 0, .external_lex_state = 4},
  [27] = {.lex_state = 0, .external_lex_state = 3},
  [28] = {.lex_state = 0, .external_lex_state = 4},
  [29] = {.lex_state = 0, .external_lex_state = 5},
  [30] = {.lex_state = 0, .external_lex_state = 4},
  [31] = {.lex_state = 0, .external_lex_state = 3},
  [32] = {.lex_state = 0, .external_lex_state = 3},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0, .external_lex_state = 8},
  [36] = {.lex_state = 0, .external_lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_colon] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [sym_arg] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [sym_dedent] = ACTIONS(1),
    [sym_text] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(34),
    [sym_heading_block] = STATE(4),
    [sym_heading_line] = STATE(20),
    [sym_task_line] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(4),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym__newline] = ACTIONS(5),
    [sym_text] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_heading_line,
    STATE(3), 3,
      sym_heading_block,
      sym_task_line,
      aux_sym_source_file_repeat1,
  [15] = 4,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_heading_line,
    STATE(6), 3,
      sym_heading_block,
      sym_task_line,
      aux_sym_source_file_repeat1,
  [30] = 4,
    ACTIONS(7), 1,
      sym_text,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    STATE(20), 1,
      sym_heading_line,
    STATE(6), 3,
      sym_heading_block,
      sym_task_line,
      aux_sym_source_file_repeat1,
  [45] = 4,
    ACTIONS(13), 1,
      sym_text,
    STATE(24), 1,
      sym_heading_line,
    STATE(36), 1,
      sym_task_block,
    STATE(7), 3,
      sym_heading_block,
      sym_task_line,
      aux_sym_source_file_repeat1,
  [60] = 4,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      sym_text,
    STATE(20), 1,
      sym_heading_line,
    STATE(6), 3,
      sym_heading_block,
      sym_task_line,
      aux_sym_source_file_repeat1,
  [75] = 4,
    ACTIONS(13), 1,
      sym_text,
    ACTIONS(20), 1,
      sym_dedent,
    STATE(24), 1,
      sym_heading_line,
    STATE(8), 3,
      sym_heading_block,
      sym_task_line,
      aux_sym_source_file_repeat1,
  [90] = 4,
    ACTIONS(15), 1,
      sym_dedent,
    ACTIONS(22), 1,
      sym_text,
    STATE(24), 1,
      sym_heading_line,
    STATE(8), 3,
      sym_heading_block,
      sym_task_line,
      aux_sym_source_file_repeat1,
  [105] = 4,
    ACTIONS(13), 1,
      sym_text,
    STATE(24), 1,
      sym_heading_line,
    STATE(35), 1,
      sym_task_block,
    STATE(7), 3,
      sym_heading_block,
      sym_task_line,
      aux_sym_source_file_repeat1,
  [120] = 4,
    ACTIONS(25), 1,
      sym_colon,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(29), 1,
      sym__newline,
    STATE(13), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [134] = 4,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      sym_colon,
    ACTIONS(33), 1,
      sym__newline,
    STATE(17), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [148] = 3,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(35), 1,
      sym__newline,
    STATE(14), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [159] = 3,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(37), 1,
      sym__newline,
    STATE(15), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [170] = 3,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(39), 1,
      sym__newline,
    STATE(15), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [181] = 3,
    ACTIONS(41), 1,
      anon_sym_AT,
    ACTIONS(44), 1,
      sym__newline,
    STATE(15), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [192] = 3,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(46), 1,
      sym__newline,
    STATE(18), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [203] = 3,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(48), 1,
      sym__newline,
    STATE(15), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [214] = 3,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(50), 1,
      sym__newline,
    STATE(15), 2,
      sym_tag,
      aux_sym_heading_line_repeat1,
  [225] = 2,
    ACTIONS(54), 1,
      sym_arg,
    ACTIONS(52), 2,
      sym__newline,
      anon_sym_AT,
  [233] = 2,
    ACTIONS(58), 1,
      sym_indent,
    ACTIONS(56), 2,
      sym_text,
      ts_builtin_sym_end,
  [241] = 1,
    ACTIONS(60), 3,
      sym_indent,
      sym_text,
      ts_builtin_sym_end,
  [247] = 1,
    ACTIONS(60), 3,
      sym_indent,
      sym_dedent,
      sym_text,
  [253] = 1,
    ACTIONS(62), 3,
      sym_indent,
      sym_dedent,
      sym_text,
  [259] = 2,
    ACTIONS(64), 1,
      sym_indent,
    ACTIONS(56), 2,
      sym_dedent,
      sym_text,
  [267] = 1,
    ACTIONS(62), 3,
      sym_indent,
      sym_text,
      ts_builtin_sym_end,
  [273] = 1,
    ACTIONS(66), 2,
      sym_dedent,
      sym_text,
  [278] = 1,
    ACTIONS(68), 2,
      sym_text,
      ts_builtin_sym_end,
  [283] = 1,
    ACTIONS(70), 2,
      sym_dedent,
      sym_text,
  [288] = 1,
    ACTIONS(72), 2,
      sym__newline,
      anon_sym_AT,
  [293] = 1,
    ACTIONS(68), 2,
      sym_dedent,
      sym_text,
  [298] = 1,
    ACTIONS(70), 2,
      sym_text,
      ts_builtin_sym_end,
  [303] = 1,
    ACTIONS(66), 2,
      sym_text,
      ts_builtin_sym_end,
  [308] = 1,
    ACTIONS(74), 1,
      sym_name,
  [312] = 1,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
  [316] = 1,
    ACTIONS(78), 1,
      sym_dedent,
  [320] = 1,
    ACTIONS(80), 1,
      sym_dedent,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 15,
  [SMALL_STATE(4)] = 30,
  [SMALL_STATE(5)] = 45,
  [SMALL_STATE(6)] = 60,
  [SMALL_STATE(7)] = 75,
  [SMALL_STATE(8)] = 90,
  [SMALL_STATE(9)] = 105,
  [SMALL_STATE(10)] = 120,
  [SMALL_STATE(11)] = 134,
  [SMALL_STATE(12)] = 148,
  [SMALL_STATE(13)] = 159,
  [SMALL_STATE(14)] = 170,
  [SMALL_STATE(15)] = 181,
  [SMALL_STATE(16)] = 192,
  [SMALL_STATE(17)] = 203,
  [SMALL_STATE(18)] = 214,
  [SMALL_STATE(19)] = 225,
  [SMALL_STATE(20)] = 233,
  [SMALL_STATE(21)] = 241,
  [SMALL_STATE(22)] = 247,
  [SMALL_STATE(23)] = 253,
  [SMALL_STATE(24)] = 259,
  [SMALL_STATE(25)] = 267,
  [SMALL_STATE(26)] = 273,
  [SMALL_STATE(27)] = 278,
  [SMALL_STATE(28)] = 283,
  [SMALL_STATE(29)] = 288,
  [SMALL_STATE(30)] = 293,
  [SMALL_STATE(31)] = 298,
  [SMALL_STATE(32)] = 303,
  [SMALL_STATE(33)] = 308,
  [SMALL_STATE(34)] = 312,
  [SMALL_STATE(35)] = 316,
  [SMALL_STATE(36)] = 320,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [20] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_block, 1, 0, 0),
  [22] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_heading_line_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [52] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 2, 0, 2),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_block, 1, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 4, 0, 1),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_line, 3, 0, 1),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_line, 2, 0, 1),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_heading_block, 4, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_task_line, 3, 0, 1),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag, 3, 0, 3),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [76] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__newline = 0,
  ts_external_token_indent = 1,
  ts_external_token_dedent = 2,
  ts_external_token_text = 3,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__newline] = sym__newline,
  [ts_external_token_indent] = sym_indent,
  [ts_external_token_dedent] = sym_dedent,
  [ts_external_token_text] = sym_text,
};

static const bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__newline] = true,
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [2] = {
    [ts_external_token__newline] = true,
    [ts_external_token_text] = true,
  },
  [3] = {
    [ts_external_token_text] = true,
  },
  [4] = {
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [5] = {
    [ts_external_token__newline] = true,
  },
  [6] = {
    [ts_external_token_indent] = true,
    [ts_external_token_text] = true,
  },
  [7] = {
    [ts_external_token_indent] = true,
    [ts_external_token_dedent] = true,
    [ts_external_token_text] = true,
  },
  [8] = {
    [ts_external_token_dedent] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_todo_external_scanner_create(void);
void tree_sitter_todo_external_scanner_destroy(void *);
bool tree_sitter_todo_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_todo_external_scanner_serialize(void *, char *);
void tree_sitter_todo_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_todo(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_todo_external_scanner_create,
      tree_sitter_todo_external_scanner_destroy,
      tree_sitter_todo_external_scanner_scan,
      tree_sitter_todo_external_scanner_serialize,
      tree_sitter_todo_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "todo",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 0,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
